package br.com.poo.hotel.visao;

import br.com.poo.hotel.controle.ItemDAO;
import br.com.poo.hotel.modelo.Categoria;
import br.com.poo.hotel.modelo.Item;
import javax.swing.JOptionPane;

/**
 *
 * @author adriane
 */
public class TelaCadastroItem extends javax.swing.JInternalFrame {

    private Item item;
    private ItemDAO dao;

    public TelaCadastroItem() {
        initComponents();
        dao = new ItemDAO();
        btnRemover.setVisible(false);
        btnSalvar.setVisible(false);
        btnAlterar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelPreco = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        labelCategoria = new javax.swing.JLabel();
        boxCategoria = new javax.swing.JComboBox();
        ftxtPreco = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        labelCodigo = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        ftxtBuscaCodigo = new javax.swing.JFormattedTextField();
        btnAlterar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Cadastro de item para consumo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do item:"));

        labelPreco.setText("Preço:");

        labelDescricao.setText("Descrição:");

        labelCategoria.setText("Categoria:");

        boxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "FRIGOBAR", "RESTAURANTE", "LAVANDERIA" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCategoria)
                            .addComponent(boxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPreco)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ftxtPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDescricao)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDescricao))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPreco)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(labelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        labelCodigo.setText("Digite o codigo:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        ftxtBuscaCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(btnRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCodigo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ftxtBuscaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(ftxtBuscaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancel)
                    .addComponent(btnRemover)
                    .addComponent(btnAlterar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (!ftxtBuscaCodigo.getText().isEmpty() && !txtDescricao.getText().isEmpty()) {

            if (boxCategoria.getSelectedItem().equals(Categoria.FRIGOBAR.toString())) {

                item = new Item(Integer.parseInt(ftxtBuscaCodigo.getText()),
                        txtDescricao.getText(), Double.parseDouble(ftxtPreco.getText()),
                        Categoria.FRIGOBAR);
                salvarItem();

            } else if (boxCategoria.getSelectedItem().equals(Categoria.LAVANDERIA.toString())) {

                item = new Item(Integer.parseInt(ftxtBuscaCodigo.getText()),
                        txtDescricao.getText(), Double.parseDouble(ftxtPreco.getText()),
                        Categoria.LAVANDERIA);
                salvarItem();

            } else if (boxCategoria.getSelectedItem().equals(Categoria.RESTAURANTE.toString())) {

                item = new Item(Integer.parseInt(ftxtBuscaCodigo.getText()),
                        txtDescricao.getText(), Double.parseDouble(ftxtPreco.getText()),
                        Categoria.RESTAURANTE);
                salvarItem();

            } else {
                JOptionPane.showMessageDialog(null, "Selecione a categoria correta para o item!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        limpar();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (ftxtBuscaCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o código a ser cadastrado!");
        }else{
            item = dao.buscaId(Integer.parseInt(ftxtBuscaCodigo.getText()));
            if (item == null) {
                JOptionPane.showMessageDialog(null, "Item não cadastrado!");
                limpar();
                btnRemover.setVisible(false);
                btnSalvar.setVisible(true);
                btnAlterar.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Item já cadastrado!");                
                setCampos();
                btnRemover.setVisible(true);
                btnSalvar.setVisible(false);
                btnAlterar.setVisible(true);
                
            }           
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        boolean resp = dao.remover(item);
        if (resp) {
            limpar();
            JOptionPane.showMessageDialog(null, "Item removido com sucesso!");
            btnAlterar.setVisible(false);
            btnRemover.setVisible(false);
            btnSalvar.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Item não removido!");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (txtDescricao.getText().isEmpty() && ftxtBuscaCodigo.getText().isEmpty() && 
                ftxtPreco.getText().isEmpty() && boxCategoria.getSelectedItem() == ""){
            JOptionPane.showMessageDialog(null, "Todos os campos devem estar devidamente preenchidos!");
        }else{
            item.setDescricao(txtDescricao.getText());
            item.setPrecoVenda(Double.parseDouble(ftxtPreco.getText()));
            
            //verificar item do combox selecionado para setar na classe
            if (boxCategoria.getSelectedItem().equals(Categoria.FRIGOBAR.toString())) {
                item.setCategoria(Categoria.FRIGOBAR);
            } else if (boxCategoria.getSelectedItem().equals(Categoria.LAVANDERIA.toString())) {
                item.setCategoria(Categoria.LAVANDERIA);
            } else if (boxCategoria.getSelectedItem().equals(Categoria.RESTAURANTE.toString())) {
                item.setCategoria(Categoria.RESTAURANTE);
            }
            
            item.setCodigo(Integer.parseInt(ftxtBuscaCodigo.getText()));
            boolean resp = dao.alterar(item);
            
            if(resp){
                JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
                limpar();
            }else{
                JOptionPane.showMessageDialog(null, "Dados não alterados!");
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    public void salvarItem() {
        
        boolean resposta = dao.inserir(item);

        if (resposta) {
            JOptionPane.showMessageDialog(null, "Item cadastrado!");
            limpar();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Item não cadastrado!");
        }
    }

    public void limpar() {
        ftxtBuscaCodigo.setText("");
        txtDescricao.setText("");
        ftxtPreco.setText("");
    }

    private void setCampos() {
        //ftxtBuscaCodigo.setText(String.valueOf(item.getCodigo()));
        txtDescricao.setText(item.getDescricao());
        ftxtPreco.setText(String.valueOf(item.getPrecoVenda()));
        boxCategoria.setSelectedItem(item.getCategoria().toString());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxCategoria;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JFormattedTextField ftxtBuscaCodigo;
    private javax.swing.JFormattedTextField ftxtPreco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
