package br.com.poo.hotel.visao;

import br.com.poo.hotel.modelo.Hospede;
import br.com.poo.hotel.modelo.Item;

/**
 *
 * @author Gêmeas
 */
public class TelaConsumacao extends javax.swing.JInternalFrame {

    private Hospede hospede;
    private Item item;
    
    public TelaConsumacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lanelDadosConsumo = new javax.swing.JPanel();
        labelData = new javax.swing.JLabel();
        labelItemConsumo = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        spinnerQuant = new javax.swing.JSpinner();
        labelValorUni = new javax.swing.JLabel();
        ftxtValorUni = new javax.swing.JFormattedTextField();
        btnBuscarItem = new javax.swing.JButton();
        ftxtIDhospede = new javax.swing.JFormattedTextField();
        labelIDhospede = new javax.swing.JLabel();
        txtNomeFunci = new javax.swing.JTextField();
        txtCodItem = new javax.swing.JTextField();
        dateData = new com.toedter.calendar.JDateChooser();
        panelDadosHospede1 = new javax.swing.JPanel();
        labelIDhospede1 = new javax.swing.JLabel();
        ftxtIDhodpede = new javax.swing.JFormattedTextField();
        btnBuscaClt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtHospede = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Consumo do hospede");

        lanelDadosConsumo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do consumo:"));

        labelData.setText("Data:");

        labelItemConsumo.setText("Item consumido:");

        labelQuantidade.setText("Quantidade:");

        labelValorUni.setText("Valor unitário:");

        ftxtValorUni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(" #,##0.00"))));

        btnBuscarItem.setText("Buscar Item");
        btnBuscarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarItemActionPerformed(evt);
            }
        });

        ftxtIDhospede.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        ftxtIDhospede.setEnabled(false);

        labelIDhospede.setText("ID funcionario:");

        txtNomeFunci.setEnabled(false);

        txtCodItem.setEnabled(false);

        javax.swing.GroupLayout lanelDadosConsumoLayout = new javax.swing.GroupLayout(lanelDadosConsumo);
        lanelDadosConsumo.setLayout(lanelDadosConsumoLayout);
        lanelDadosConsumoLayout.setHorizontalGroup(
            lanelDadosConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lanelDadosConsumoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lanelDadosConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lanelDadosConsumoLayout.createSequentialGroup()
                        .addGroup(lanelDadosConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lanelDadosConsumoLayout.createSequentialGroup()
                                .addComponent(ftxtIDhospede, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(txtNomeFunci))
                            .addGroup(lanelDadosConsumoLayout.createSequentialGroup()
                                .addComponent(txtCodItem, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnBuscarItem)
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addGroup(lanelDadosConsumoLayout.createSequentialGroup()
                                .addGroup(lanelDadosConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelQuantidade)
                                    .addComponent(spinnerQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(lanelDadosConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelValorUni)
                                    .addComponent(ftxtValorUni, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(lanelDadosConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lanelDadosConsumoLayout.createSequentialGroup()
                                        .addComponent(labelData)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(dateData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(lanelDadosConsumoLayout.createSequentialGroup()
                        .addGroup(lanelDadosConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelItemConsumo)
                            .addComponent(labelIDhospede))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        lanelDadosConsumoLayout.setVerticalGroup(
            lanelDadosConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lanelDadosConsumoLayout.createSequentialGroup()
                .addComponent(labelItemConsumo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lanelDadosConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lanelDadosConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidade)
                    .addComponent(labelValorUni)
                    .addComponent(labelData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lanelDadosConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lanelDadosConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spinnerQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftxtValorUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(labelIDhospede)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lanelDadosConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeFunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtIDhospede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelDadosHospede1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do hospede:"));

        labelIDhospede1.setText("ID hospede:");

        ftxtIDhodpede.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        ftxtIDhodpede.setEnabled(false);

        btnBuscaClt.setText("Buscar");
        btnBuscaClt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCltActionPerformed(evt);
            }
        });

        txtHospede.setColumns(20);
        txtHospede.setRows(5);
        txtHospede.setEnabled(false);
        jScrollPane2.setViewportView(txtHospede);

        javax.swing.GroupLayout panelDadosHospede1Layout = new javax.swing.GroupLayout(panelDadosHospede1);
        panelDadosHospede1.setLayout(panelDadosHospede1Layout);
        panelDadosHospede1Layout.setHorizontalGroup(
            panelDadosHospede1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosHospede1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosHospede1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIDhospede1)
                    .addGroup(panelDadosHospede1Layout.createSequentialGroup()
                        .addComponent(ftxtIDhodpede, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnBuscaClt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelDadosHospede1Layout.setVerticalGroup(
            panelDadosHospede1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosHospede1Layout.createSequentialGroup()
                .addComponent(labelIDhospede1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosHospede1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtIDhodpede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaClt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAdd.setText("Adicionar ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jButton1.setText("Remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDadosHospede1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lanelDadosConsumo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDadosHospede1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lanelDadosConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBuscaCltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCltActionPerformed
        TelaPesquisa pesquisa = new TelaPesquisa(this, 1);
        ftxtIDhodpede.setText(hospede.getCpf());
        txtHospede.setText(hospede.getNome());               
    }//GEN-LAST:event_btnBuscaCltActionPerformed

    private void btnBuscarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarItemActionPerformed
        TelaPesquisa window = new TelaPesquisa(this, 2);
        txtCodItem.setText(String.valueOf(item.getCodigo())+" - "+item.getDescricao());
        ftxtValorUni.setText(String.valueOf(item.getPrecoVenda()));
        
    }//GEN-LAST:event_btnBuscarItemActionPerformed

    public Hospede getHospede(){
        return hospede;
    }
    public void setHospede(Hospede hospede){
        this.hospede = hospede;
    }
    
    public Item getItem(){
        return item;
    }
    public void setItem(Item item){
        this.item = item;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBuscaClt;
    private javax.swing.JButton btnBuscarItem;
    private javax.swing.JButton btnCancel;
    private com.toedter.calendar.JDateChooser dateData;
    private javax.swing.JFormattedTextField ftxtIDhodpede;
    private javax.swing.JFormattedTextField ftxtIDhospede;
    private javax.swing.JFormattedTextField ftxtValorUni;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelIDhospede;
    private javax.swing.JLabel labelIDhospede1;
    private javax.swing.JLabel labelItemConsumo;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelValorUni;
    private javax.swing.JPanel lanelDadosConsumo;
    private javax.swing.JPanel panelDadosHospede1;
    private javax.swing.JSpinner spinnerQuant;
    private javax.swing.JTextField txtCodItem;
    private javax.swing.JTextArea txtHospede;
    private javax.swing.JTextField txtNomeFunci;
    // End of variables declaration//GEN-END:variables
}
