package br.com.poo.hotel.visao;

import br.com.poo.hotel.controle.AcomodacaoDAO;
import br.com.poo.hotel.controle.HospedeDAO;
import br.com.poo.hotel.controle.ItemDAO;
import br.com.poo.hotel.modelo.Hospede;
import br.com.poo.hotel.modelo.Item;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
                   
/**
 *
 * @author Schick
 */
public class TelaPesquisa extends javax.swing.JInternalFrame {
    
    private Object tela;
    private int tipo;
    private TableModel model;
    
    
    
    public TelaPesquisa(Object obj, int tipo) {
        this.tipo = tipo;
        tela = obj;
        initComponents();
        Inicio();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtPesquisa = new javax.swing.JTable();
        lblFiltro = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        btnSelecionar = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jScrollPane2.setViewportView(jtPesquisa);

        lblFiltro.setText("Filtro:");

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblFiltro)
                        .addGap(18, 18, 18)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltro)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiltrar)
                    .addComponent(btnVoltar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Inicio(){
        if(tipo == 1){
            List<Hospede> h;
            HospedeDAO dao = new HospedeDAO();
            h = dao.listar();
            if(!h.isEmpty()){
                jtPesquisa.setModel(new TableModelHospede(h));
            }else{
                //JOptionPane.showMessageDialog(this,"Não possui nenhum Hóspede cadastrado");
                this.dispose();
            }
        }else{
            if(tipo == 2){
                List<Item> i;
                ItemDAO dao = new ItemDAO();
                i = dao.listar();
                jtPesquisa.setModel(new TableModelItem(dao.listar()));
            }else{
                AcomodacaoDAO dao = new AcomodacaoDAO();
                jtPesquisa.setModel(new TableModelAcomodacao(dao.listar()));
                btnFiltrar.setVisible(false);
                txtFiltro.setVisible(false);     
            }
        }
    }
    
     private void retornaAcomodacao(int retorno){
         AcomodacaoDAO dao = new AcomodacaoDAO();            
         TelaFazerReserva t = (TelaFazerReserva) tela;
         t.setAcomodacao(dao.buscaPorID(retorno));
         this.dispose();   
    }
    
    private void retornaHospede(String retorno){
         HospedeDAO dao = new HospedeDAO();
         if(tela instanceof TelaFazerReserva){
            TelaFazerReserva t = (TelaFazerReserva) tela;
            t.setHospede(dao.buscarID(retorno));
            t.trocar();
         }else{
            TelaConsumacao t = (TelaConsumacao) tela;
            t.setHospede (dao.buscarID(retorno));
            t.trocar();
         }
         this.dispose();
    }
    
    private void retornaItem(int retorno){
         ItemDAO dao = new ItemDAO();            
         TelaConsumacao t = (TelaConsumacao) tela;
         t.setItem(dao.buscaId(retorno));
         this.dispose();
    }
    
    private void Filtrar(String filtro){
        if(!filtro.equals("")){
            if(tipo == 1){
                HospedeDAO dao = new HospedeDAO();
                model = (TableModelHospede)new TableModelHospede(dao.buscarNome(filtro));
            }else{
                ItemDAO dao = new ItemDAO();
                model = (TableModelItem)new TableModelItem(dao.listar());
            }
        }else{
            Inicio();
        }
        jtPesquisa.setModel(model);
    }
    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        int linha = jtPesquisa.getSelectedRow();
        
        if(tipo == 1){
            retornaHospede((String)jtPesquisa.getValueAt(linha,0));
        }else{
            if(tipo == 2){
                retornaItem((Integer)jtPesquisa.getValueAt(linha, 0));
            }else{
                retornaAcomodacao((Integer)jtPesquisa.getValueAt(linha, 0));
            }
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        Filtrar(txtFiltro.getText());
    }//GEN-LAST:event_btnFiltrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtPesquisa;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables

}