package br.com.poo.hotel.visao;

import br.com.poo.hotel.controle.TipoAcomodacaoDAO;
import br.com.poo.hotel.modelo.TipoAcomodacao;
import javax.swing.JOptionPane;
import org.omg.CORBA.TCKind;

/**
 *
 * @author adriane
 */
public class TelaCadastroTipoAcomodacao extends javax.swing.JInternalFrame {

    private TipoAcomodacaoDAO tipoDAO;
    private TipoAcomodacao tipo;
    
    public TelaCadastroTipoAcomodacao() {
        initComponents();
        tipoDAO = new TipoAcomodacaoDAO();
        btnRemover.setVisible(false);
        btnSalvar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTipoAcomodacao = new javax.swing.JLabel();
        btntipoAcomodacao = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelDescricao = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        spinnerNroAcomodacoes = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spinnerCriancas = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spinnerNroAdultos = new javax.swing.JSpinner();
        ftxtValorDiaria = new javax.swing.JFormattedTextField();
        txtDescricao = new javax.swing.JTextField();
        btnRemover = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        ftxtCodigoTipo = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Alterar tipo de acomodação");

        labelTipoAcomodacao.setText("Digite o codigo do tipo de acomodação:");

        btntipoAcomodacao.setText("Buscar");
        btntipoAcomodacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntipoAcomodacaoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do tipo de acomodação:"));

        labelDescricao.setText("Descrição:");

        labelQuantidade.setText("Quantidade:");

        spinnerNroAcomodacoes.setEnabled(false);

        jLabel1.setText("Valor da diária:");

        jLabel2.setText("Nº de crianças:");

        spinnerCriancas.setEnabled(false);

        jLabel3.setText("Nº de adultos:");

        spinnerNroAdultos.setEnabled(false);

        ftxtValorDiaria.setEnabled(false);

        txtDescricao.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescricao)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelQuantidade)
                            .addComponent(spinnerNroAcomodacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ftxtValorDiaria)
                                .addGap(2, 2, 2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(spinnerCriancas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerNroAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(0, 102, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtDescricao)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidade)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerNroAcomodacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerCriancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerNroAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTipoAcomodacao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ftxtCodigoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btntipoAcomodacao, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTipoAcomodacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntipoAcomodacao)
                    .addComponent(ftxtCodigoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSalvar)
                    .addComponent(btnRemover))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntipoAcomodacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntipoAcomodacaoActionPerformed
        if (ftxtCodigoTipo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o codigo do tipo da acomodação!");
        }else{
            tipo = tipoDAO.buscarID(Integer.parseInt(ftxtCodigoTipo.getText()));
            if (tipo == null){
                JOptionPane.showMessageDialog(null, "Tipo de acomodação não cadastro!");
                ftxtValorDiaria.setEnabled(true);
                txtDescricao.setEnabled(true);
                spinnerCriancas.setEnabled(true);
                spinnerNroAdultos.setEnabled(true);
                spinnerNroAcomodacoes.setEnabled(true);
                btnSalvar.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Tipo de acomodação já cadastrada!");
                ftxtValorDiaria.setText(String.valueOf(tipo.getPrecoDiaria()));
                txtDescricao.setText(tipo.getDescricao());
                spinnerCriancas.setValue(tipo.getNumeroCriancas());
                spinnerNroAdultos.setValue(tipo.getNumeroAdultos());
                spinnerNroAcomodacoes.setValue(tipo.getQuantidade());
                ftxtValorDiaria.setEnabled(true);
                txtDescricao.setEnabled(true);
                spinnerNroAdultos.setEnabled(true);
                spinnerCriancas.setEnabled(true);
                spinnerNroAcomodacoes.setEnabled(true);
                btnSalvar.setVisible(false);
                btnRemover.setVisible(true);
                
            }
        }
    }//GEN-LAST:event_btntipoAcomodacaoActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        boolean resp = tipoDAO.remover(tipo);
        if (resp){
            JOptionPane.showMessageDialog(null, "Remoção feita com sucesso!");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível remover o tipo de acomodação!");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(ftxtCodigoTipo.getText().isEmpty() && ftxtValorDiaria.getText().isEmpty() && spinnerCriancas.getValue().equals(0)
           && spinnerNroAcomodacoes.getValue().equals(0) && spinnerNroAdultos.getValue().equals(0) && txtDescricao.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }else{            
            tipo = new TipoAcomodacao(Integer.parseInt(ftxtCodigoTipo.getText()), txtDescricao.getText(), 
                                        (int) spinnerNroAcomodacoes.getValue(), Double.valueOf((ftxtValorDiaria.getText())), 
                                        (int) spinnerNroAdultos.getValue(), (int) spinnerCriancas.getValue());
            boolean resp = tipoDAO.inserir(tipo);
            
            if(resp){
                JOptionPane.showMessageDialog(null, "Tipo de acomodação foi cadastrado com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null, "Tipo de acomodação não foi cadastrado!");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btntipoAcomodacao;
    private javax.swing.JFormattedTextField ftxtCodigoTipo;
    private javax.swing.JFormattedTextField ftxtValorDiaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelTipoAcomodacao;
    private javax.swing.JSpinner spinnerCriancas;
    private javax.swing.JSpinner spinnerNroAcomodacoes;
    private javax.swing.JSpinner spinnerNroAdultos;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
