package br.com.poo.hotel.visao;

import br.com.poo.hotel.controle.HospedeDAO;
import br.com.poo.hotel.controle.ItemDAO;
                   
/**
 *
 * @author Schick
 */
public class TelaPesquisa extends javax.swing.JInternalFrame {
    
    private Object tela;
    private int tipo;
    
    
    /**
     * Creates new form TelaPesquisa
     */
    public TelaPesquisa(Object obj, int tipo) {
        this.tipo = tipo;
        tela = obj;
        Inicio();
        initComponents();      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtPesquisa = new javax.swing.JTable();
        lblFiltro = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnSelecionar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jtPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtPesquisa);

        lblFiltro.setText("Filtro:");

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblFiltro)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltro)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Inicio(){
        if(tipo == 1){
            HospedeDAO dao = new HospedeDAO();
            jtPesquisa.setModel(new TableModelHospede(dao.listar()));
        }else{
            ItemDAO dao = new ItemDAO();
            jtPesquisa.setModel(new TableModelItem(dao.listar()));
        }
    }
    
    private void retornaHospede(String retorno){
         HospedeDAO dao = new HospedeDAO();
         if(tela instanceof TelaReserva){
            TelaReserva t = (TelaReserva) tela;
            t.setHospede(dao.buscar(retorno));
         }else{
            TelaConsumacao t = (TelaConsumacao) tela;
            t.setHospede (dao.buscar(retorno));
         }
    }
    
    private void retornaItem(int retorno){
         ItemDAO dao = new ItemDAO();
         if(tela instanceof TelaConsumacao){
            TelaConsumacao t = (TelaConsumacao) tela;
            t.setItem(dao.buscaId(retorno));
         }
    }
    
    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        int linha = jtPesquisa.getSelectedRow();
        
        if(tipo == 1){
            retornaHospede((String)jtPesquisa.getValueAt(linha,1));
        }else{
            retornaItem((Integer)jtPesquisa.getValueAt(linha, 1));
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jtPesquisa;
    private javax.swing.JLabel lblFiltro;
    // End of variables declaration//GEN-END:variables

}