package br.com.poo.hotel.visao;

import br.com.poo.hotel.controle.ReservaDAO;
import br.com.poo.hotel.modelo.Acomodacao;
import br.com.poo.hotel.modelo.Acompanhante;
import br.com.poo.hotel.modelo.CartaoCredito;
import br.com.poo.hotel.modelo.Hospede;
import br.com.poo.hotel.modelo.Reserva;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author adriane
 */
public class TelaFazerReserva extends javax.swing.JInternalFrame {

    private Acomodacao acomodacao;
    private CartaoCredito card;
    private Hospede hospede;        
    private Acompanhante acompanhante;    
    private Principal add;
    private Reserva reserva;
    private ReservaDAO reservaDAO;
    private List<Acompanhante> listaAcompanhante;    
    
    public TelaFazerReserva(Principal add) {
        initComponents();                
        listaAcompanhante = new ArrayList<>();
        reservaDAO = new ReservaDAO();      
        this.add = add;                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dateDataEntrada = new com.toedter.calendar.JDateChooser();
        ftxtHoraEntrada = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelDataSaida = new javax.swing.JLabel();
        dateDataSaida = new com.toedter.calendar.JDateChooser();
        labelHoraSaida = new javax.swing.JLabel();
        ftxtHoraSaida = new javax.swing.JFormattedTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Cartão = new javax.swing.JPanel();
        labelNroCartao = new javax.swing.JLabel();
        ftxtNroCartao = new javax.swing.JFormattedTextField();
        labelNroAgencia = new javax.swing.JLabel();
        ftxtNroAgencia = new javax.swing.JFormattedTextField();
        Acompanhantes = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        ftxtIdade = new javax.swing.JFormattedTextField();
        labelIdade = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtClt = new javax.swing.JTextArea();
        labelIDclt = new javax.swing.JLabel();
        labelAcomodação = new javax.swing.JLabel();
        labelDiaria = new javax.swing.JLabel();
        labelMulta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ftxtDesconto = new javax.swing.JFormattedTextField();
        ftxtDiaria = new javax.swing.JFormattedTextField();
        ftxtMulta = new javax.swing.JFormattedTextField();
        btnAcomodacao = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAcomodacao = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle("Reserva de Acomodação");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados da reserva:"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Chegada prevista:"));

        jLabel3.setText("Data");

        ftxtHoraEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jLabel4.setText("Hora:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(dateDataEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(ftxtHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Saída prevista:"));

        labelDataSaida.setText("Data:");

        labelHoraSaida.setText("Hora:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateDataSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(labelDataSaida)
                    .addComponent(labelHoraSaida)
                    .addComponent(ftxtHoraSaida))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelDataSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHoraSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtHoraSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do hospede:"));

        labelNroCartao.setText("Nº do cartão:");

        labelNroAgencia.setText("Nº da agência:");

        javax.swing.GroupLayout CartãoLayout = new javax.swing.GroupLayout(Cartão);
        Cartão.setLayout(CartãoLayout);
        CartãoLayout.setHorizontalGroup(
            CartãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartãoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CartãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNroCartao)
                    .addComponent(ftxtNroCartao, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(labelNroAgencia)
                    .addComponent(ftxtNroAgencia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CartãoLayout.setVerticalGroup(
            CartãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartãoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNroCartao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtNroCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNroAgencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtNroAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cartão", Cartão);

        labelNome.setText("Nome:");

        labelIdade.setText("Idade:");

        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AcompanhantesLayout = new javax.swing.GroupLayout(Acompanhantes);
        Acompanhantes.setLayout(AcompanhantesLayout);
        AcompanhantesLayout.setHorizontalGroup(
            AcompanhantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcompanhantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AcompanhantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AcompanhantesLayout.createSequentialGroup()
                        .addGroup(AcompanhantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome)
                            .addComponent(labelIdade))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AcompanhantesLayout.createSequentialGroup()
                        .addComponent(ftxtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        AcompanhantesLayout.setVerticalGroup(
            AcompanhantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcompanhantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AcompanhantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(ftxtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Acompanhantes", Acompanhantes);

        btnBuscarCliente.setText("Buscar ");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        txtClt.setColumns(20);
        txtClt.setRows(5);
        txtClt.setEnabled(false);
        jScrollPane1.setViewportView(txtClt);

        labelIDclt.setText("ID Cliente:");

        labelAcomodação.setText("Acomodação:");

        labelDiaria.setText("Valor da diária:");

        labelMulta.setText("Multa:");

        jLabel2.setText("Desconto:");

        btnAcomodacao.setText("Buscar");
        btnAcomodacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcomodacaoActionPerformed(evt);
            }
        });

        txtAcomodacao.setColumns(20);
        txtAcomodacao.setRows(5);
        txtAcomodacao.setText("\n");
        jScrollPane2.setViewportView(txtAcomodacao);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelIDclt)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxtDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDiaria))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMulta))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(labelAcomodação)
                    .addComponent(btnAcomodacao)
                    .addComponent(btnBuscarCliente)
                    .addComponent(jScrollPane2))
                .addGap(183, 183, 183))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelIDclt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(labelAcomodação)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAcomodacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDiaria)
                            .addComponent(labelMulta)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxtDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancel))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        TelaPesquisa pesquisa = new TelaPesquisa(this, 1);
        add.addDesktop(pesquisa);     
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(!String.valueOf(dateDataEntrada.getDate()).isEmpty() && !String.valueOf(dateDataEntrada.getDate()).isEmpty() &&
                !ftxtHoraEntrada.getText().isEmpty() && !ftxtHoraSaida.getText().isEmpty()
                && !ftxtNroAgencia.getText().isEmpty() && !ftxtNroCartao.getText().isEmpty()
                && !txtClt.getText().isEmpty()){
            
            reserva = new Reserva(dateDataEntrada.getDate(), dateDataSaida.getDate(), Integer.parseInt(ftxtMulta.getText()), 
                    Integer.parseInt(ftxtDesconto.getText()), acomodacao, null, hospede);
            boolean resp = reservaDAO.inserir(reserva);
            if(resp){
                JOptionPane.showMessageDialog(null, "Reserva feita com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null, "Reserva não foi feita!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        ftxtHoraEntrada.setText("");
        ftxtHoraSaida.setText("");
        ftxtIdade.setText("");
        ftxtNroAgencia.setText("");
        ftxtNroCartao.setText("");        
        txtNome.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (!txtNome.getText().isEmpty() && !ftxtIdade.getText().isEmpty()) {
            acompanhante = new Acompanhante(txtNome.getText(), Integer.parseInt(ftxtIdade.getText()));

            /*if (listaAcompanhante.size() <= acomodacao.getTipoAcomodacao().getNumeroAdultos()
                    + acomodacao.getTipoAcomodacao().getNumeroCriancas()) {*/
                boolean resp = listaAcompanhante.add(acompanhante);
                if (resp) {
                    JOptionPane.showMessageDialog(null, "Acompanhante adicionado!");
                } else {
                    JOptionPane.showMessageDialog(null, "Acompanhante não adicionado!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Número máximo de acompanhantes foi atingido!");
            }
        //}
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAcomodacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcomodacaoActionPerformed
        TelaPesquisa pesquisa = new TelaPesquisa(this, 3);
        add.addDesktop(pesquisa);       
    }//GEN-LAST:event_btnAcomodacaoActionPerformed

    public void trocar(){        
        txtClt.setText("Nome: "+hospede.getNome()+"\nCPF: "+hospede.getCpf());  
    }
    
    public void trocarAcomodacao(){        
        txtClt.setText("Código: "+acomodacao.getCodigo()+"\nTipo: "+acomodacao.getTipoAcomodacao());  
    }
    
    public Hospede getHospede(){
        return hospede;
    }
    public void setHospede(Hospede hospede){
        this.hospede = hospede;
    }
    
    public Acomodacao getAcomodacao(){
        return acomodacao;
    }
    public void setAcomodacao(Acomodacao acomodacao){
        this.acomodacao = acomodacao;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acompanhantes;
    private javax.swing.JPanel Cartão;
    private javax.swing.JButton btnAcomodacao;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSalvar;
    private com.toedter.calendar.JDateChooser dateDataEntrada;
    private com.toedter.calendar.JDateChooser dateDataSaida;
    private javax.swing.JFormattedTextField ftxtDesconto;
    private javax.swing.JFormattedTextField ftxtDiaria;
    private javax.swing.JFormattedTextField ftxtHoraEntrada;
    private javax.swing.JFormattedTextField ftxtHoraSaida;
    private javax.swing.JFormattedTextField ftxtIdade;
    private javax.swing.JFormattedTextField ftxtMulta;
    private javax.swing.JFormattedTextField ftxtNroAgencia;
    private javax.swing.JFormattedTextField ftxtNroCartao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAcomodação;
    private javax.swing.JLabel labelDataSaida;
    private javax.swing.JLabel labelDiaria;
    private javax.swing.JLabel labelHoraSaida;
    private javax.swing.JLabel labelIDclt;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JLabel labelMulta;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNroAgencia;
    private javax.swing.JLabel labelNroCartao;
    private javax.swing.JTextArea txtAcomodacao;
    private javax.swing.JTextArea txtClt;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
